import type { Metadata, Viewport } from "next"
import localFont from "next/font/local"
import "./globals.css"
import { Toaster } from "@/components/ui/toaster"
import { PwaInstallBanner } from "@/components/pwa-install-banner"
import { SwUpdateToast } from "@/components/sw-update-toast"
import { SplashScreen } from "@/components/splash-screen"
import { PushPermissionPrompt } from "@/components/push-permission-prompt"

const inter = localFont({
  src: "../public/fonts/inter-latin-var.woff2",
  variable: "--font-body",
  display: "swap",
})
const spaceGrotesk = localFont({
  src: "../public/fonts/space-grotesk-latin-var.woff2",
  variable: "--font-display",
  display: "swap",
})

export const metadata: Metadata = {
  title: "VortexChat — Chat, Hang Out, Belong",
  description: "The chat platform for focused teams and creative communities",
  icons: {
    icon: [
      { url: "/favicon.ico?v=2", sizes: "48x48" },
      { url: "/favicon-16x16.png?v=2", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png?v=2", sizes: "32x32", type: "image/png" },
      { url: "/icon-192.png?v=2", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png?v=2", sizes: "512x512", type: "image/png" },
    ],
    apple: { url: "/apple-touch-icon.png?v=2", sizes: "180x180", type: "image/png" },
    shortcut: "/favicon.ico?v=2",
  },
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "VortexChat",
  },
  openGraph: {
    title: "VortexChat — Chat, Hang Out, Belong",
    description: "The chat platform for focused teams and creative communities",
    siteName: "VortexChat",
    type: "website",
    images: [{ url: "/og-image.png", width: 1200, height: 630, alt: "VortexChat" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "VortexChat — Chat, Hang Out, Belong",
    description: "The chat platform for focused teams and creative communities",
    images: ["/og-image.png"],
  },
}

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  viewportFit: "cover",
  interactiveWidget: "resizes-content",
  themeColor: "#00e5ff",
}

/** Top-level HTML shell — applies Inter (body) + Space Grotesk (display/headings), dark theme, and global toast notifications.
 *  force-dynamic is required because proxy.ts generates a per-request nonce for CSP;
 *  static caching would serve stale nonces and cause CSP violations. */
export const dynamic = "force-dynamic"

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}): Promise<React.ReactElement> {
  // Read the CSP nonce generated by proxy.ts so Next.js can apply it to
  // inline scripts. Without this, the strict CSP policy blocks all JS.
  const { headers } = await import("next/headers")
  let nonce = ""
  try {
    nonce = (await headers()).get("x-nonce") ?? ""
  } catch {
    // headers() unavailable — fall back to empty nonce
  }

  return (
    <html lang="en" className="dark" suppressHydrationWarning nonce={nonce}>
      <head>
        <meta name="color-scheme" content="dark" />
        <meta name="format-detection" content="telephone=no" />
        {/* Preconnect to Supabase — saves ~100-300ms on first API call (DNS + TLS) */}
        {process.env.NEXT_PUBLIC_SUPABASE_URL && (
          <link rel="preconnect" href={process.env.NEXT_PUBLIC_SUPABASE_URL} />
        )}
        {/* DNS-prefetch for third-party origins used later in the session */}
        <link rel="dns-prefetch" href="https://fonts.gstatic.com" />
        <link rel="dns-prefetch" href="https://cdn.jsdelivr.net" />
        <link rel="dns-prefetch" href="https://api.giphy.com" />
        <link rel="apple-touch-startup-image" href="/startup/apple-splash-1170-2532.png" media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)" />
        <link rel="apple-touch-startup-image" href="/startup/apple-splash-1284-2778.png" media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3)" />
        <link rel="apple-touch-startup-image" href="/startup/apple-splash-1125-2436.png" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)" />
        <link rel="apple-touch-startup-image" href="/startup/apple-splash-1242-2688.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)" />
        <link rel="apple-touch-startup-image" href="/startup/apple-splash-1536-2048.png" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)" />
        <link rel="apple-touch-startup-image" href="/startup/apple-splash-1668-2224.png" media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)" />
        <link rel="apple-touch-startup-image" href="/startup/apple-splash-2048-2732.png" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)" />
        <link rel="apple-touch-startup-image" href="/startup/apple-splash-1290-2796.png" media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)" />
        <link rel="apple-touch-startup-image" href="/startup/apple-splash-1179-2556.png" media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3)" />
        <link rel="apple-touch-startup-image" href="/startup/apple-splash-1206-2622.png" media="(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3)" />
        <link rel="apple-touch-startup-image" href="/startup/apple-splash-1320-2868.png" media="(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3)" />
      </head>
      <body className={`${inter.variable} ${spaceGrotesk.variable} font-sans`} style={{ background: "var(--theme-bg-primary)" }} suppressHydrationWarning>
        <a href="#main-content" className="skip-nav-link">Skip to main content</a>
        <SplashScreen />
        {children}
        <Toaster />
        <PwaInstallBanner />
        <SwUpdateToast />
        <PushPermissionPrompt />
      </body>
    </html>
  )
}
