#!/usr/bin/env bash
set -euo pipefail

##############################################################################
#  VortexChat Self-Hosted Setup Script
#
#  Generates secrets, validates configuration, and prepares the .env file
#  for a self-hosted deployment.
#
#  Usage:
#    chmod +x scripts/setup.sh
#    ./scripts/setup.sh
#
#  Then:  docker compose up -d
##############################################################################

ENV_FILE=".env"

# ─── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

info()  { echo -e "${CYAN}[info]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ok]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*"; }
err()   { echo -e "${RED}[error]${NC} $*"; }

# ─── Header ─────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}┌─────────────────────────────────────────────┐${NC}"
echo -e "${BOLD}│       VortexChat Self-Hosted Setup           │${NC}"
echo -e "${BOLD}└─────────────────────────────────────────────┘${NC}"
echo ""

# ─── Check prerequisites ────────────────────────────────────────────────────
check_command() {
  if ! command -v "$1" &>/dev/null; then
    err "$1 is required but not installed."
    exit 1
  fi
}

check_command docker
check_command openssl
info "Prerequisites OK (docker, openssl)"

# ─── Generate secrets ────────────────────────────────────────────────────────
gen_secret() { openssl rand -hex 32; }

CRON_SECRET=$(gen_secret)
STEP_UP_SECRET=$(gen_secret)
SIGNAL_REVOKE_SECRET=$(gen_secret)

info "Generated CRON_SECRET, STEP_UP_SECRET, SIGNAL_REVOKE_SECRET"

# ─── Generate VAPID keys ────────────────────────────────────────────────────
generate_vapid() {
  if command -v npx &>/dev/null; then
    info "Generating VAPID keys for Web Push..."
    local output
    output=$(npx --yes web-push generate-vapid-keys --json 2>/dev/null || echo "")
    if [ -n "$output" ]; then
      VAPID_PUBLIC_KEY=$(echo "$output" | node -e "const d=require('fs').readFileSync('/dev/stdin','utf8'); const j=JSON.parse(d); console.log(j.publicKey)" 2>/dev/null || echo "")
      VAPID_PRIVATE_KEY=$(echo "$output" | node -e "const d=require('fs').readFileSync('/dev/stdin','utf8'); const j=JSON.parse(d); console.log(j.privateKey)" 2>/dev/null || echo "")
      if [ -n "$VAPID_PUBLIC_KEY" ] && [ -n "$VAPID_PRIVATE_KEY" ]; then
        ok "VAPID keys generated"
        return
      fi
    fi
  fi
  warn "Could not generate VAPID keys automatically."
  warn "Run 'npx web-push generate-vapid-keys' manually and add to .env"
  VAPID_PUBLIC_KEY=""
  VAPID_PRIVATE_KEY=""
}

generate_vapid

# ─── Interactive prompts ─────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}Configure your database connection:${NC}"
echo "  This can be Supabase Cloud, self-hosted Supabase, or any Postgres"
echo "  instance with the Supabase client libraries."
echo ""

read_with_default() {
  local prompt="$1"
  local default="$2"
  local varname="$3"
  if [ -n "$default" ]; then
    echo -ne "  ${prompt} [${default}]: "
  else
    echo -ne "  ${prompt}: "
  fi
  read -r input
  printf -v "$varname" '%s' "${input:-$default}"
}

read_with_default "Supabase URL" "" SUPABASE_URL
read_with_default "Supabase anon key" "" SUPABASE_ANON_KEY
read_with_default "Supabase service role key" "" SUPABASE_SERVICE_ROLE_KEY
echo ""
read_with_default "App URL (where users access VortexChat)" "http://localhost:3000" APP_URL
echo ""

# ─── Signal server URL ──────────────────────────────────────────────────────
# Default to ws://localhost:3001 for single-machine deployments
SIGNAL_DEFAULT="ws://localhost:3001"
if [[ "$APP_URL" != *"localhost"* ]]; then
  SIGNAL_DEFAULT=""
fi
read_with_default "Signal server WebSocket URL" "$SIGNAL_DEFAULT" SIGNAL_URL

# ─── Write .env ─────────────────────────────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
  warn ".env already exists — backing up to .env.backup"
  cp "$ENV_FILE" "${ENV_FILE}.backup"
fi

cat > "$ENV_FILE" <<ENVEOF
# ─── VortexChat Self-Hosted Configuration ─────────────────────────────────
# Generated by scripts/setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# ─── Database (Supabase) ─────────────────────────────────────────────────
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
SUPABASE_URL=${SUPABASE_URL}

# ─── App URLs ────────────────────────────────────────────────────────────
NEXT_PUBLIC_APP_URL=${APP_URL}
NEXT_PUBLIC_SIGNAL_URL=${SIGNAL_URL}

# ─── Secrets (auto-generated) ────────────────────────────────────────────
CRON_SECRET=${CRON_SECRET}
STEP_UP_SECRET=${STEP_UP_SECRET}
SIGNAL_REVOKE_SECRET=${SIGNAL_REVOKE_SECRET}

# ─── Web Push (VAPID) ───────────────────────────────────────────────────
NEXT_PUBLIC_VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
VAPID_SUBJECT=mailto:admin@example.com

# ─── Redis ───────────────────────────────────────────────────────────────
# Managed by docker-compose — override only if using an external Redis.
# REDIS_URL=redis://redis:6379

# ─── Optional services (uncomment and configure as needed) ───────────────

# TURN server (WebRTC NAT traversal — needed for ~20% of users)
# TURN_URL=turn:your-turn-server:3478
# TURN_SECRET=your-coturn-static-auth-secret
# TURNS_URL=turns:your-turn-server:5349

# LiveKit (optional SFU for voice channels — P2P WebRTC works without it)
# LIVEKIT_API_KEY=your-livekit-api-key
# LIVEKIT_API_SECRET=your-livekit-api-secret
# NEXT_PUBLIC_LIVEKIT_URL=wss://your-livekit-server

# GIF providers (optional — picker hidden when not configured)
# KLIPY_API_KEY=your-klipy-api-key
# GIPHY_API_KEY=your-giphy-api-key

# Error monitoring (optional)
# NEXT_PUBLIC_SENTRY_DSN=https://your-key@oXXXXXX.ingest.sentry.io/XXXXXXX

# Social connections (optional)
# STEAM_WEB_API_KEY=your-steam-web-api-key
# GOOGLE_CLIENT_ID=your-google-client-id
# GOOGLE_CLIENT_SECRET=your-google-client-secret
ENVEOF

ok ".env written"

# ─── Validation ──────────────────────────────────────────────────────────────
echo ""
info "Validating configuration..."

errors=0

validate_set() {
  local name="$1"
  local value="$2"
  if [ -z "$value" ]; then
    err "  $name is not set"
    errors=$((errors + 1))
  else
    ok "  $name"
  fi
}

validate_set "NEXT_PUBLIC_SUPABASE_URL" "$SUPABASE_URL"
validate_set "NEXT_PUBLIC_SUPABASE_ANON_KEY" "$SUPABASE_ANON_KEY"
validate_set "SUPABASE_SERVICE_ROLE_KEY" "$SUPABASE_SERVICE_ROLE_KEY"
validate_set "NEXT_PUBLIC_APP_URL" "$APP_URL"
validate_set "CRON_SECRET" "$CRON_SECRET"
validate_set "STEP_UP_SECRET" "$STEP_UP_SECRET"

if [ -z "$VAPID_PUBLIC_KEY" ] || [ -z "$VAPID_PRIVATE_KEY" ]; then
  warn "  VAPID keys not set — push notifications will be disabled"
fi

if [ "$errors" -gt 0 ]; then
  echo ""
  err "$errors required variable(s) missing — edit .env before starting"
  exit 1
fi

# ─── Done ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}Setup complete!${NC}"
echo ""
echo "  Next steps:"
echo "    1. Review and edit .env if needed"
echo "    2. Make sure your database migrations are applied:"
echo "       npx supabase db push  (or apply supabase/migrations/ manually)"
echo "    3. Start VortexChat:"
echo "       docker compose up -d"
echo ""
echo "    Web:    ${APP_URL}"
echo "    Signal: ${SIGNAL_URL}"
echo ""
