"use client"

// Post-call summary card — shown after a session ends when summary_status = 'ready'.
// Displays three required sections: Highlights, Decisions, Action Items.

import { useState, useEffect } from "react"
import { FileText, Loader2, ChevronDown, ChevronUp } from "lucide-react"
import type { VoiceCallSummaryRow } from "@/types/vortex-recap"

interface VoiceSummaryCardProps {
  sessionId: string
  /** If true, the component polls until the summary is ready. */
  summaryPending: boolean
  className?: string
}

export function VoiceSummaryCard({ sessionId, summaryPending, className }: VoiceSummaryCardProps) {
  const [summary, setSummary] = useState<VoiceCallSummaryRow | null>(null)
  const [loading, setLoading] = useState(summaryPending)
  const [expanded, setExpanded] = useState(true)

  useEffect(() => {
    if (!summaryPending && !summary) return

    let cancelled = false

    async function fetchSummary() {
      try {
        const res = await fetch(`/api/voice/sessions/${sessionId}/summary`)
        if (!res.ok || cancelled) return

        const data = (await res.json()) as { summary: VoiceCallSummaryRow | null; status: string }
        if (data.status === "ready" && data.summary) {
          setSummary(data.summary)
          setLoading(false)
        } else if (data.status === "failed" || data.status === "skipped") {
          setLoading(false)
        }
        // Still pending — will be re-triggered by next summaryPending change
      } catch {
        // Non-fatal
      }
    }

    fetchSummary()

    return () => {
      cancelled = true
    }
  }, [sessionId, summaryPending, summary])

  if (!summaryPending && !summary) return null

  return (
    <div
      className={`rounded-lg overflow-hidden ${className ?? ""}`}
      style={{ background: "var(--theme-bg-secondary)", border: "1px solid var(--theme-bg-tertiary)" }}
    >
      {/* Header */}
      <button
        className="w-full flex items-center justify-between gap-2 px-4 py-3 transition-colors hover:bg-white/5"
        onClick={() => setExpanded((e) => !e)}
        aria-expanded={expanded}
        aria-label={expanded ? "Collapse voice recap" : "Expand voice recap"}
      >
        <div className="flex items-center gap-2">
          <FileText className="w-4 h-4" style={{ color: "var(--theme-accent)" }} />
          <span className="text-sm font-semibold text-white">Vortex Recap</span>
          {loading && <Loader2 className="w-3 h-3 animate-spin" style={{ color: "var(--theme-text-secondary)" }} />}
        </div>
        {expanded ? (
          <ChevronUp className="w-4 h-4" style={{ color: "var(--theme-text-secondary)" }} />
        ) : (
          <ChevronDown className="w-4 h-4" style={{ color: "var(--theme-text-secondary)" }} />
        )}
      </button>

      {expanded && (
        <div className="px-4 pb-4 flex flex-col gap-4">
          {loading && !summary ? (
            <p className="text-sm" style={{ color: "var(--theme-text-secondary)" }}>
              Generating summary…
            </p>
          ) : summary ? (
            <>
              <SummarySection title="Highlights" content={summary.highlights_md} />
              <SummarySection title="Decisions" content={summary.decisions_md} />
              <SummarySection title="Action Items" content={summary.action_items_md} />
              <p className="text-xs" style={{ color: "var(--theme-text-faint)" }}>
                Generated by {summary.model} &middot;{" "}
                {new Date(summary.generated_at).toLocaleString()}
              </p>
            </>
          ) : (
            <p className="text-sm" style={{ color: "var(--theme-text-secondary)" }}>
              Summary unavailable.
            </p>
          )}
        </div>
      )}
    </div>
  )
}

function SummarySection({ title, content }: { title: string; content: string }) {
  if (!content.trim()) return null
  return (
    <div>
      <h4 className="text-xs font-semibold uppercase tracking-wide mb-1" style={{ color: "var(--theme-accent)" }}>
        {title}
      </h4>
      <p className="text-sm whitespace-pre-wrap leading-relaxed" style={{ color: "var(--theme-text-primary)" }}>
        {content}
      </p>
    </div>
  )
}
